name: Planetoids
main: org.canis85.planetoidgen.PlanetoidGen
version: 1.3.1_b
description: Creates a world full of planets.
author: Canis85 (modded by Niphred)
load: startup
commands:
    pltp:
        description: Moves the player to/from the planetoids area
        usage: /pltp
